insert into public.psychologists (
  slug,
  name_th,
  name_en,
  nickname_th,
  nickname_en,
  license_no,
  photo_url,
  approach_th,
  approach_en,
  value_th,
  value_en,
  quote_th,
  quote_en,
  topics,
  active,
  sort_order
)
values
(
  'panida-yomabut',
  'พณิดา โยมะบุตร',
  'Panida Yomabut',
  'ดาว',
  'Dao',
  'จค. 462',
  '/psychologists/psycho1.png',
  'จิตวิทยาแบบผสมผสาน',
  'Integrative Therapy',
  'ความสงบภายในใจ',
  'Peace of Mind',
  'เราทุกคนมีศักยภาพในการก้าวข้าม ผ่านช่วงเวลายากลำบากได้มากกว่าที่เราคิด',
  'We all have more potential to move through difficult times than we often realize.',
  array['relationships', 'adjustment', 'emotions', 'behavior', 'thinking', 'personality']::text[],
  true,
  0
),
(
  'anuttra-ranee',
  'อนุตตรา รานี',
  'Anuttra Ranee',
  'ชีเกนส์',
  'Chigains',
  'จค. 1385',
  '/psychologists/psycho2.png',
  'Satir Model และ CBT',
  'Satir Model & CBT',
  'พื้นที่ปลอดภัยทางอารมณ์',
  'Emotional Safe Space',
  'เราทุกคนมีศักยภาพในการก้าวข้าม ผ่านช่วงเวลายากลำบากได้มากกว่าที่เราคิด',
  'We all have more potential to move through difficult times than we often realize.',
  array['relationships', 'adjustment', 'emotions', 'stress', 'depression', 'work']::text[],
  true,
  1
),
(
  'suchitraphak-srisupanrat',
  'สุจิตรภัค ศรีสุพรรณราช',
  'Suchitraphak Srisupanrat',
  'กานพลู',
  'Karnplu',
  'จค. 1400',
  '/psychologists/psycho3.png',
  'การบำบัดแบบประคับประคอง',
  'Supportive Psychotherapy',
  'คุณค่าและอัตลักษณ์ของผู้รับบริการ',
  'Case''s Value and Identity',
  'ดอกไม้ทุกดอกมีความสวยงาม เพียงแค่รอเวลาและสิ่งแวดล้อมที่เหมาะสมในการผลิบาน',
  'Every flower has its own beauty, waiting for the right time and environment to bloom.',
  array['relationships', 'adjustment', 'emotions', 'stress', 'work']::text[],
  true,
  2
),
(
  'jitti-kunkamthonwong',
  'จิตติ กันกำธรวงศ์',
  'Jitti Kunkamthonwong',
  'ฉิ่น',
  'Chin',
  'จค. 1562',
  '/psychologists/psycho4.png',
  'แนวทางมนุษยนิยม',
  'Humanistic Approach',
  'ความมุ่งมั่น',
  'Determination',
  'ขอแค่เราไม่ยอมแพ้ เราก็ยังลุกขึ้นมาลองใหม่ได้เสมอ',
  'As long as we do not give up, we can always stand up and try again.',
  array['relationships', 'adjustment', 'emotions', 'stress', 'depression', 'work']::text[],
  true,
  3
)
on conflict (slug) do update
set
  name_th = excluded.name_th,
  name_en = excluded.name_en,
  nickname_th = excluded.nickname_th,
  nickname_en = excluded.nickname_en,
  license_no = excluded.license_no,
  photo_url = excluded.photo_url,
  approach_th = excluded.approach_th,
  approach_en = excluded.approach_en,
  value_th = excluded.value_th,
  value_en = excluded.value_en,
  quote_th = excluded.quote_th,
  quote_en = excluded.quote_en,
  topics = excluded.topics,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();
